---
format_version: 10
environments:
  internal:
    pipelines:
      - gocd-cli
pipelines:
  gocd-cli:
    group: go-cd-contrib
    materials:
      github:
        git: https://git.gocd.io/git/gocd-contrib/gocd-cli
    stages:
      - build:
          elastic_profile_id: ecs-golang-build
          tasks:
            - script: |
                set -eux
                ./build.sh --verbose --prod --release=1.0.0
                echo "Collating binaries..."
                sha256sum dist/darwin/amd64/gocd
                sha256sum dist/linux/amd64/gocd
                sha256sum dist/windows/amd64/gocd.exe
                zip -r clis.zip dist
          artifacts:
            - build:
                source: win-cli.zip
